/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MawloudIndexRouteImport } from './routes/mawloud.index'
import { Route as MawloudSettingsRouteImport } from './routes/mawloud.settings'

const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MawloudIndexRoute = MawloudIndexRouteImport.update({
  id: '/mawloud/',
  path: '/mawloud/',
  getParentRoute: () => rootRouteImport,
} as any)
const MawloudSettingsRoute = MawloudSettingsRouteImport.update({
  id: '/mawloud/settings',
  path: '/mawloud/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud/': typeof MawloudIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud': typeof MawloudIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud/': typeof MawloudIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/designs' | '/mawloud/settings' | '/mawloud/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/designs' | '/mawloud/settings' | '/mawloud'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/designs'
    | '/mawloud/settings'
    | '/mawloud/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DesignsRoute: typeof DesignsRoute
  MawloudSettingsRoute: typeof MawloudSettingsRoute
  MawloudIndexRoute: typeof MawloudIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mawloud/': {
      id: '/mawloud/'
      path: '/mawloud'
      fullPath: '/mawloud/'
      preLoaderRoute: typeof MawloudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mawloud/settings': {
      id: '/mawloud/settings'
      path: '/mawloud/settings'
      fullPath: '/mawloud/settings'
      preLoaderRoute: typeof MawloudSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DesignsRoute: DesignsRoute,
  MawloudSettingsRoute: MawloudSettingsRoute,
  MawloudIndexRoute: MawloudIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
