/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappUnblockRouteImport } from './routes/whatsapp-unblock'
import { Route as SpeedTestRouteImport } from './routes/speed-test'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PhoneBillInquiryRouteImport } from './routes/phone-bill-inquiry'
import { Route as DialCodesRouteImport } from './routes/dial-codes'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdslInquiryRouteImport } from './routes/adsl-inquiry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MawloudIndexRouteImport } from './routes/mawloud.index'
import { Route as MawloudSettingsRouteImport } from './routes/mawloud.settings'

const WhatsappUnblockRoute = WhatsappUnblockRouteImport.update({
  id: '/whatsapp-unblock',
  path: '/whatsapp-unblock',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedTestRoute = SpeedTestRouteImport.update({
  id: '/speed-test',
  path: '/speed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneBillInquiryRoute = PhoneBillInquiryRouteImport.update({
  id: '/phone-bill-inquiry',
  path: '/phone-bill-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DialCodesRoute = DialCodesRouteImport.update({
  id: '/dial-codes',
  path: '/dial-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdslInquiryRoute = AdslInquiryRouteImport.update({
  id: '/adsl-inquiry',
  path: '/adsl-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MawloudIndexRoute = MawloudIndexRouteImport.update({
  id: '/mawloud/',
  path: '/mawloud/',
  getParentRoute: () => rootRouteImport,
} as any)
const MawloudSettingsRoute = MawloudSettingsRouteImport.update({
  id: '/mawloud/settings',
  path: '/mawloud/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adsl-inquiry': typeof AdslInquiryRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/dial-codes': typeof DialCodesRoute
  '/phone-bill-inquiry': typeof PhoneBillInquiryRoute
  '/services': typeof ServicesRoute
  '/speed-test': typeof SpeedTestRoute
  '/whatsapp-unblock': typeof WhatsappUnblockRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud/': typeof MawloudIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adsl-inquiry': typeof AdslInquiryRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/dial-codes': typeof DialCodesRoute
  '/phone-bill-inquiry': typeof PhoneBillInquiryRoute
  '/services': typeof ServicesRoute
  '/speed-test': typeof SpeedTestRoute
  '/whatsapp-unblock': typeof WhatsappUnblockRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud': typeof MawloudIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adsl-inquiry': typeof AdslInquiryRoute
  '/auth': typeof AuthRoute
  '/designs': typeof DesignsRoute
  '/dial-codes': typeof DialCodesRoute
  '/phone-bill-inquiry': typeof PhoneBillInquiryRoute
  '/services': typeof ServicesRoute
  '/speed-test': typeof SpeedTestRoute
  '/whatsapp-unblock': typeof WhatsappUnblockRoute
  '/mawloud/settings': typeof MawloudSettingsRoute
  '/mawloud/': typeof MawloudIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adsl-inquiry'
    | '/auth'
    | '/designs'
    | '/dial-codes'
    | '/phone-bill-inquiry'
    | '/services'
    | '/speed-test'
    | '/whatsapp-unblock'
    | '/mawloud/settings'
    | '/mawloud/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adsl-inquiry'
    | '/auth'
    | '/designs'
    | '/dial-codes'
    | '/phone-bill-inquiry'
    | '/services'
    | '/speed-test'
    | '/whatsapp-unblock'
    | '/mawloud/settings'
    | '/mawloud'
  id:
    | '__root__'
    | '/'
    | '/adsl-inquiry'
    | '/auth'
    | '/designs'
    | '/dial-codes'
    | '/phone-bill-inquiry'
    | '/services'
    | '/speed-test'
    | '/whatsapp-unblock'
    | '/mawloud/settings'
    | '/mawloud/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdslInquiryRoute: typeof AdslInquiryRoute
  AuthRoute: typeof AuthRoute
  DesignsRoute: typeof DesignsRoute
  DialCodesRoute: typeof DialCodesRoute
  PhoneBillInquiryRoute: typeof PhoneBillInquiryRoute
  ServicesRoute: typeof ServicesRoute
  SpeedTestRoute: typeof SpeedTestRoute
  WhatsappUnblockRoute: typeof WhatsappUnblockRoute
  MawloudSettingsRoute: typeof MawloudSettingsRoute
  MawloudIndexRoute: typeof MawloudIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-unblock': {
      id: '/whatsapp-unblock'
      path: '/whatsapp-unblock'
      fullPath: '/whatsapp-unblock'
      preLoaderRoute: typeof WhatsappUnblockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-test': {
      id: '/speed-test'
      path: '/speed-test'
      fullPath: '/speed-test'
      preLoaderRoute: typeof SpeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-bill-inquiry': {
      id: '/phone-bill-inquiry'
      path: '/phone-bill-inquiry'
      fullPath: '/phone-bill-inquiry'
      preLoaderRoute: typeof PhoneBillInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dial-codes': {
      id: '/dial-codes'
      path: '/dial-codes'
      fullPath: '/dial-codes'
      preLoaderRoute: typeof DialCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adsl-inquiry': {
      id: '/adsl-inquiry'
      path: '/adsl-inquiry'
      fullPath: '/adsl-inquiry'
      preLoaderRoute: typeof AdslInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mawloud/': {
      id: '/mawloud/'
      path: '/mawloud'
      fullPath: '/mawloud/'
      preLoaderRoute: typeof MawloudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mawloud/settings': {
      id: '/mawloud/settings'
      path: '/mawloud/settings'
      fullPath: '/mawloud/settings'
      preLoaderRoute: typeof MawloudSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdslInquiryRoute: AdslInquiryRoute,
  AuthRoute: AuthRoute,
  DesignsRoute: DesignsRoute,
  DialCodesRoute: DialCodesRoute,
  PhoneBillInquiryRoute: PhoneBillInquiryRoute,
  ServicesRoute: ServicesRoute,
  SpeedTestRoute: SpeedTestRoute,
  WhatsappUnblockRoute: WhatsappUnblockRoute,
  MawloudSettingsRoute: MawloudSettingsRoute,
  MawloudIndexRoute: MawloudIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
